#!/usr/bin/python3

import argparse

from parser import evaparser
from src.interpreter import Eva

def evalGlobal(code: str):
    expr = evaparser.parse(f'(begin {code})')
    return Eva().evalGlobal(expr)

argparser = argparse.ArgumentParser(description='===== EVA language AST-interpreter =====')
argparser.add_argument('-e', '--evaluate-expression',
                        dest='expr',
                        action='store',
                        type=str,
                        help='evaluate passed expression')
argparser.add_argument('-f', '--file',
                        dest='file',
                        action='store',
                        type=str,
                        help='execute program from file')

if __name__ == '__main__':
    args = argparser.parse_args()

    if args.expr:
        evalGlobal(args.expr)
    if args.file:
        with open(args.file, 'r') as srcFile:
            moduleSrc = srcFile.read()
        evalGlobal(moduleSrc)
